INIT_PROC PCP.prc 1
INIT_PROC PHP.prc 1
INIT_PROC PMP.prc 1
INIT_PROC SCHED_MEM.prc 1
INIT_PROC MEM_PRE_0.prc 1
INIT_PROC SCHED_PRE_0.prc 1
INIT_PROC PCP.prc 1
INIT_PROC PHP.prc 1
INIT_PROC PMP.prc 1
INIT_PROC SCHED_MEM.prc 1
INIT_PROC MEM_PRE_0.prc 1
INIT_PROC SCHED_PRE_0.prc 1
EXIT