NOOP
MUTEX_CREATE MUTEX_1
MUTEX_CREATE MUTEX_2
MUTEX_CREATE MUTEX_3
NOOP
NOOP
INIT_PROC PRIORITY_INHERITANCE_1.prc 5
INIT_PROC PRIORITY_INHERITANCE_2.prc 4
SLEEP 10000
INIT_PROC PRIORITY_INHERITANCE_3.prc 3
INIT_PROC PRIORITY_INHERITANCE_3.prc 3
INIT_PROC PRIORITY_INHERITANCE_3.prc 3
INIT_PROC PRIORITY_INHERITANCE_3.prc 3
INIT_PROC PRIORITY_INHERITANCE_3.prc 3
NOOP
INIT_PROC PRIORITY_INHERITANCE_4.prc 2
NOOP
NOOP
INIT_PROC PRIORITY_INHERITANCE_5.prc 1
EXIT