NOOP
MUTEX_CREATE MUTEX_1
MUTEX_CREATE MUTEX_2
NOOP
INIT_PROC PRIORITY_INHERITANCE_V2_1.prc 5
SLEEP 2000
INIT_PROC PRIORITY_INHERITANCE_V2_2.prc 3
SLEEP 2000
INIT_PROC PRIORITY_INHERITANCE_V2_4.prc 2
INIT_PROC PRIORITY_INHERITANCE_V2_3.prc 1
EXIT