NOOP
INIT_PROC SHORT_TERM_1.prc 3
INIT_PROC SHORT_TERM_1.prc 3
INIT_PROC SHORT_TERM_1.prc 3
INIT_PROC SHORT_TERM_1.prc 3
NOOP
NOOP
INIT_PROC SHORT_TERM_2.prc 2
INIT_PROC SHORT_TERM_2.prc 2
NOOP
NOOP
INIT_PROC SHORT_TERM_3.prc 1
EXIT