INIT_PROC SHORT_TERM.prc 1
INIT_PROC SHORT_TERM.prc 1
INIT_PROC PRIORITY_INHERITANCE.prc 1
INIT_PROC PRIORITY_INHERITANCE.prc 1
INIT_PROC SCHED_MEM.prc 1
INIT_PROC SCHED_MEM.prc 1
SLEEP 2000
SET PC 0
EXIT