NOOP
INIT_PROC proceso1.asm 3
INIT_PROC proceso1.asm 3
INIT_PROC proceso1.asm 3
INIT_PROC proceso1.asm 3
INIT_PROC proceso1.asm 3
SET AX 6
SET BX 2
SUM AX BX
SUB AX BX
JNZ AX 12
SET AX 6
MEM_ALLOC 0 64
COPY_MEM AX
MOV_IN EDX
MOV_OUT EDX
MUTEX_CREATE MUTEX_1
MUTEX_LOCK MUTEX_1
MUTEX_UNLOCK MUTEX_1
MEM_FREE 0
SLEEP 2500
STDOUT AX BX
STDIN CX DX
INIT_PROC proceso1.asm 3
EXIT
